- src/main/java/com/team1/otvoo/exception/Code.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/java/com/team1/otvoo/exception/ErrorResponse.java
- src/main/java/com/team1/otvoo/exception/GlobalExceptionHandler.java
- src/main/java/com/team1/otvoo/exception/RestException.java
KAN-15
- 기본 예외 처리 구현
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] feature: KAN-15 기본 예외 처리 구현

- src/main/resources/schema.sql
KAN-30
- 프로젝트 공통 파일 작업
어떤 변경 사항이 있나요?
> [프로젝트 초기설] fix: KAN-30 users 테이블에 누락된 속성 추가

- src/main/resources/schema.sql
KAN-28
- 프로젝트 초기 설정 누락된 부분 추가
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] fix: KAN-28 프로젝트 초기 설정 누락된 부분 추가

- src/main/java/com/team1/otvoo/user/dto/AuthorDto.java
- src/main/java/com/team1/otvoo/user/dto/ChangePasswordRequest.java
- src/main/java/com/team1/otvoo/user/dto/Location.java
- src/main/java/com/team1/otvoo/user/dto/ProfileDto.java
- src/main/java/com/team1/otvoo/user/dto/ProfileUpdateRequest.java
- src/main/java/com/team1/otvoo/user/dto/UserCreateRequest.java
- src/main/java/com/team1/otvoo/user/dto/UserDto.java
- src/main/java/com/team1/otvoo/user/dto/UserDtoCursorResponse.java
- src/main/java/com/team1/otvoo/user/dto/UserLockUpdateRequest.java
- src/main/java/com/team1/otvoo/user/dto/UserRoleUpdateRequest.java
- src/main/java/com/team1/otvoo/user/dto/UserSummary.java
- src/main/java/com/team1/otvoo/user/entity/Gender.java
- src/main/java/com/team1/otvoo/user/entity/Profile.java
- src/main/java/com/team1/otvoo/user/entity/ProfileImage.java
- src/main/java/com/team1/otvoo/user/entity/Role.java
- src/main/java/com/team1/otvoo/user/entity/User.java
KAN-37
- 사용자 관련 entity, dto 추가
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] feat: KAN-37 사용자

- src/main/java/com/team1/otvoo/weather/dto/HumidityDto.java
- src/main/java/com/team1/otvoo/weather/dto/PrecipitationDto.java
- src/main/java/com/team1/otvoo/weather/dto/TemperatureDto.java
- src/main/java/com/team1/otvoo/weather/dto/WeatherAPILocation.java
- src/main/java/com/team1/otvoo/weather/dto/WeatherDto.java
- src/main/java/com/team1/otvoo/weather/dto/WeatherSummaryDto.java
- src/main/java/com/team1/otvoo/weather/dto/WindSpeedDto.java
- src/main/java/com/team1/otvoo/weather/entity/PrecipitationType.java
- src/main/java/com/team1/otvoo/weather/entity/SkyStatus.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherForecast.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherHumidity.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherLocation.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherPrecipitation.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherTemperature.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherWindSpeed.java
- src/main/java/com/team1/otvoo/weather/entity/WindStrength.java
> [프로젝트 초기 설정] feat: KAN-39 날씨 데이터

- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefDtoCursorResponse.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefUpdateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeWithDefDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesDtoCursorResponse.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesUpdateRequest.java
- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesAttributeDefinition.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesAttributeValue.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesSelectedValue.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesType.java
KAN-40
의상 관련 entity, dto 구현
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] feat: KAN-40 의상 관리

- src/main/java/com/team1/otvoo/exception/ErrorResponse.java
- src/main/java/com/team1/otvoo/exception/GlobalExceptionHandler.java
KAN-45
- errorResponse 수정
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] fix: KAN-45 프로젝트 초기 설정-errorResponse 수정

- src/main/java/com/team1/otvoo/comment/dto/CommentCreateRequest.java
- src/main/java/com/team1/otvoo/comment/dto/CommentDto.java
- src/main/java/com/team1/otvoo/comment/entity/FeedComment.java
- src/main/java/com/team1/otvoo/feed/dto/FeedCreateRequest.java
- src/main/java/com/team1/otvoo/feed/dto/FeedDto.java
- src/main/java/com/team1/otvoo/feed/dto/FeedUpdateRequest.java
- src/main/java/com/team1/otvoo/feed/entity/Feed.java
- src/main/java/com/team1/otvoo/feed/entity/FeedLike.java
- src/main/resources/schema.sql
KAN-68
- KAN-69 피드 entity, dto 구현
- KAN-72 피드 테이블 comment_count 컬럼 추가
- KAN-70 댓글 entity, dto 구현
- KAN-71 좋아요 entity 구현
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] feat: KAN-68 피드

- src/main/java/com/team1/otvoo/feed/dto/FeedDto.java
- src/main/java/com/team1/otvoo/recommendation/dto/OotdDto.java
- src/main/java/com/team1/otvoo/recommendation/dto/RecommendationDto.java
- src/main/java/com/team1/otvoo/recommendation/dto/RecommendedClothesDto.java
- src/main/java/com/team1/otvoo/recommendation/entity/Recommendation.java
- src/main/java/com/team1/otvoo/recommendation/entity/RecommendationClothes.java
- src/main/resources/schema.sql
KAN-76
스키마 파일수정
의상추천 관련 DTO 및 엔티티 생성
어떤 변경 사항이 있나요?
> [프로젝트 초기 설정] feat: KAN-76 의상 추천

- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/java/com/team1/otvoo/user/controller/UserController.java
- src/main/java/com/team1/otvoo/user/dto/ChangePasswordRequest.java
- src/main/java/com/team1/otvoo/user/entity/Profile.java
- src/main/java/com/team1/otvoo/user/entity/ProfileImage.java
- src/main/java/com/team1/otvoo/user/entity/User.java
- src/main/java/com/team1/otvoo/user/service/UserService.java
- src/main/java/com/team1/otvoo/user/service/UserServiceImpl.java
- src/main/java/com/team1/otvoo/user/util/UserMapper.java
- src/test/java/com/team1/otvoo/user/controller/UserControllerTest.java
- src/test/java/com/team1/otvoo/user/service/UserServiceImplTest.java
- src/test/java/com/team1/otvoo/user/util/TestUtils.java
- src/test/java/com/team1/otvoo/user/util/UserMapperTest.java
KAN-54 
- 비밀번호 변경 구현
어떤 변경 사항이 있나요?
> [사용자 관리] feat: KAN-54 비밀번호 변경 구현

- src/main/java/com/team1/otvoo/follow/controller/FollowController.java
- src/main/java/com/team1/otvoo/follow/dto/FollowDto.java
- src/main/java/com/team1/otvoo/follow/entity/Follow.java
- src/main/java/com/team1/otvoo/follow/mapper/FollowMapper.java
- src/main/java/com/team1/otvoo/follow/repository/FollowRepository.java
- src/main/java/com/team1/otvoo/follow/service/FollowService.java
- src/main/java/com/team1/otvoo/follow/service/impl/FollowServiceImpl.java
- src/main/java/com/team1/otvoo/user/entity/User.java
- src/test/java/com/team1/otvoo/follow/service/FollowServiceTest.java
KAN-10
팔로우 생성/삭제 기능 구현
어떤 변경 사항이 있나요?
> [팔로우] feat: KAN-10 팔로우 생성 삭제

- src/main/java/com/team1/otvoo/weather/entity/WeatherForecast.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherHumidity.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherLocation.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherPrecipitation.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherTemperature.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherWindSpeed.java
- src/main/java/com/team1/otvoo/weather/repository/WeatherForecastRepository.java
- src/main/java/com/team1/otvoo/weather/repository/custom/WeatherForecastRepositoryCustom.java
- src/main/java/com/team1/otvoo/weather/repository/impl/WeatherForecastRepositoryImpl.java
KAN-62
엔티티 수정
레포지토리 생성
QueryDSL 기반 커스텀 쿼리 구현체 생성
어떤 변경 사항이 있나요?
> [날씨 데이터 관리] feat: KAN-62 날씨 데이터 저장소 구현

- src/main/java/com/team1/otvoo/auth/controller/AuthController.java
- src/main/java/com/team1/otvoo/auth/service/AuthService.java
- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
- src/main/java/com/team1/otvoo/interceptor/HttpHandshakeInterceptor.java
- src/main/java/com/team1/otvoo/security/JwtTokenProvider.java
- src/main/java/com/team1/otvoo/security/SecurityConfig.java
KAN-135
JWT 기반 로그아웃 API 구현
어떤 변경 사항이 있나요?
> [인증 관리] feat: KAN-135 JWT 기반 로그아웃 API 구현

- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/java/com/team1/otvoo/user/controller/UserController.java
- src/main/java/com/team1/otvoo/user/dto/SortBy.java
- src/main/java/com/team1/otvoo/user/dto/SortDirection.java
- src/main/java/com/team1/otvoo/user/dto/UserDtoCursorRequest.java
- src/main/java/com/team1/otvoo/user/dto/UserDtoCursorResponse.java
- src/main/java/com/team1/otvoo/user/dto/UserSlice.java
- src/main/java/com/team1/otvoo/user/mapper/UserMapper.java
- src/main/java/com/team1/otvoo/user/repository/UserQueryDslRepository.java
- src/main/java/com/team1/otvoo/user/repository/UserQueryDslRepositoryImpl.java
- src/main/java/com/team1/otvoo/user/repository/UserRepository.java
- src/main/java/com/team1/otvoo/user/service/UserService.java
- src/main/java/com/team1/otvoo/user/service/UserServiceImpl.java
- src/test/java/com/team1/otvoo/user/controller/UserControllerTest.java
- src/test/java/com/team1/otvoo/user/mapper/TestUtils.java
- src/test/java/com/team1/otvoo/user/mapper/UserMapperTest.java
- src/test/java/com/team1/otvoo/user/service/UserServiceImplTest.java
KAN-126 
- 계정 목록 조회
어떤 변경 사항이 있나요?
> [사용자 관리] feat: KAN-126 계정 목록 조회

- src/main/java/com/team1/otvoo/auth/controller/AuthController.java
- src/main/java/com/team1/otvoo/auth/service/AuthService.java
- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
KAN-136
액세스 토큰 조회 API 구현
어떤 변경 사항이 있나요?
> [인증 관리] feat: KAN-136 액세스 토큰 조회 API 구현

- src/main/java/com/team1/otvoo/auth/controller/AuthController.java
- src/main/java/com/team1/otvoo/auth/service/AuthService.java
- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
KAN-137
토큰 재발급 API 구현
어떤 변경 사항이 있나요?
> [인증 관리] feat: KAN-137 토큰 재발급 API 구현

- src/main/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefController.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesAttributeDefUpdateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesDto.java
- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesAttributeDefinition.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesAttributeValue.java
- src/main/java/com/team1/otvoo/clothes/mapper/ClothesAttributeDefMapper.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeDefRepository.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefService.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImpl.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefControllerTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImplTest.java
KAN-55
의상 등록,수정,삭제 기능 구현
테스트 코드 구현
어떤 변경 사항이 있나요?
> [의상 관리] feat: KAN-55 의상 속성 등록 수정 삭제

- src/main/java/com/team1/otvoo/config/DefaultProfileImageProperties.java
- src/main/java/com/team1/otvoo/user/controller/UserController.java
- src/main/java/com/team1/otvoo/user/entity/Profile.java
- src/main/java/com/team1/otvoo/user/resolver/ProfileImageUrlResolver.java
- src/main/java/com/team1/otvoo/user/service/ProfileImageService.java
- src/main/java/com/team1/otvoo/user/service/ProfileImageServiceImpl.java
- src/main/java/com/team1/otvoo/user/service/UserService.java
- src/main/java/com/team1/otvoo/user/service/UserServiceImpl.java
- src/main/resources/application.yml
- src/test/java/com/team1/otvoo/user/controller/UserControllerTest.java
- src/test/java/com/team1/otvoo/user/resolver/ProfileImageUrlResolverTest.java
- src/test/java/com/team1/otvoo/user/service/ProfileImageServiceImplTest.java
- src/test/java/com/team1/otvoo/user/service/UserServiceImplTest.java
KAN-181 
- 프로필 업데이트
어떤 변경 사항이 있나요?
> [사용자 관리] feat: KAN-181 프로필 업데이트

- src/main/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefController.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesDto.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesUpdateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/OotdDto.java
- src/main/java/com/team1/otvoo/clothes/dto/SortBy.java
- src/main/java/com/team1/otvoo/clothes/dto/SortDirection.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDefCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDefDto.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDefDtoCursorResponse.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDefSearchCondition.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDefUpdateRequest.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeDto.java
- src/main/java/com/team1/otvoo/clothes/dto/clothesAttributeDef/ClothesAttributeWithDefDto.java
- src/main/java/com/team1/otvoo/clothes/mapper/ClothesAttributeDefMapper.java
- src/main/java/com/team1/otvoo/clothes/mapper/ClothesMapper.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeDefRepository.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeDefRepositoryCustom.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeDefRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesRepository.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefService.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImpl.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/java/com/team1/otvoo/recommendation/dto/OotdDto.java
- src/test/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefControllerTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImplTest.java
KAN-56
Clothes/ClothesAttributeDef dto 패키지 분리
의상 속성 목록 조회 커서 페이지네이션 구현
service, controller 테스트 코드 작성
어떤 변경 사항이 있나요?
> [의상 관리] feat: KAN-56 의상 속성 목록 조회

- src/main/java/com/team1/otvoo/auth/token/AccessTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RedisAccessTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RedisRefreshTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RefreshTokenStore.java
- src/main/java/com/team1/otvoo/security/JwtAuthenticationFilter.java
- src/main/java/com/team1/otvoo/security/JwtLoginSuccessHandler.java
- src/main/java/com/team1/otvoo/security/JwtLogoutHandler.java
- src/main/java/com/team1/otvoo/security/JwtTokenProvider.java
- src/main/java/com/team1/otvoo/security/SecurityConfig.java
- src/main/resources/application.yml
KAN-238
Redis 저장 로직 분리 및 구조 개선
어떤 변경 사항이 있나요?
> [인증 관리] refactor: KAN-238 Redis 저장 로직 분리 및 구조 개선

- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesSelectedValue.java
- src/main/java/com/team1/otvoo/clothes/mapper/ClothesMapper.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/java/com/team1/otvoo/feed/controller/FeedController.java
- src/main/java/com/team1/otvoo/feed/dto/FeedDto.java
- src/main/java/com/team1/otvoo/feed/mapper/FeedMapper.java
- src/main/java/com/team1/otvoo/feed/mapper/FeedPageResponseMapper.java
- src/main/java/com/team1/otvoo/feed/repository/FeedClothesRepository.java
- src/main/java/com/team1/otvoo/feed/repository/FeedRepositoryCustom.java
- src/main/java/com/team1/otvoo/feed/repository/FeedRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/feed/service/FeedServiceImpl.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/feed/repository/FeedClothesRepositoryTest.java
- src/test/java/com/team1/otvoo/feed/repository/FeedRepositoryCustomImplTest.java
- src/test/java/com/team1/otvoo/feed/service/FeedServiceTest.java
KAN-220
- 도메인별 에러코드 세분화
- User - Profile - ProfileImage 관계 변화에 따른 피드 목록 조회 QueryDsl Dto Projection 기반 리팩토링
- 피드 목록 조회 단위테스트 수정
- FeedClothesRepository 단위테스트 작성
어떤 변경 사항이 있나요?
> [피드 관리] feat: KAN-220 피드 목록 조회 리팩토링

- src/main/java/com/team1/otvoo/clothes/dto/ClothesDto.java
- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesImage.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesSelectedValue.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesImageRepository.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesImageService.java
- src/main/resources/schema.sql
KAN-259
의상 이미지 도메인 분리
- ClothesImage 엔티티/DDL/Repository/Service 생성
어떤 변경 사항이 있나요?
> [의상 관리] feat: KAN-259 의상 이미지 도메인 설계

- src/main/java/com/team1/otvoo/auth/controller/AuthController.java
- src/main/java/com/team1/otvoo/auth/dto/SignInRequest.java
- src/main/java/com/team1/otvoo/auth/dto/SignInResponse.java
- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
- src/main/java/com/team1/otvoo/auth/token/AccessTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RedisAccessTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RedisRefreshTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/RedisTemporaryPasswordStore.java
- src/main/java/com/team1/otvoo/auth/token/RefreshTokenStore.java
- src/main/java/com/team1/otvoo/auth/token/TemporaryPasswordStore.java
- src/main/java/com/team1/otvoo/interceptor/HttpHandshakeInterceptor.java
- src/main/java/com/team1/otvoo/interceptor/WebSocketChannelInterceptor.java
- src/main/java/com/team1/otvoo/security/CustomAuthenticationProvider.java
- src/main/java/com/team1/otvoo/security/CustomUserDetails.java
- src/main/java/com/team1/otvoo/security/JwtAuthenticationFilter.java
- src/main/java/com/team1/otvoo/security/JwtLoginSuccessHandler.java
- src/main/java/com/team1/otvoo/security/JwtLogoutHandler.java
- src/main/java/com/team1/otvoo/security/JwtTokenProvider.java
- src/main/java/com/team1/otvoo/security/SecurityConfig.java
KAN-255
- userId token 타입 string -> UUID로 변경  
- WebSocket 연결 및 재연결 로직 개선  
- Refresh token 쿠키에 저장 추가
어떤 변경 사항이 있나요?
> [인증 관리] refactor: KAN-255 코드 리팩토링 및 웹소켓, 토큰 처리 개선

- src/main/java/com/team1/otvoo/feed/controller/FeedLikeController.java
- src/main/java/com/team1/otvoo/feed/entity/FeedLike.java
- src/main/java/com/team1/otvoo/feed/repository/FeedLikeRepository.java
- src/main/java/com/team1/otvoo/feed/repository/FeedRepository.java
- src/main/java/com/team1/otvoo/feed/repository/FeedRepositoryCustom.java
- src/main/java/com/team1/otvoo/feed/repository/FeedRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/feed/service/FeedLikeService.java
- src/main/java/com/team1/otvoo/feed/service/FeedLikeServiceImpl.java
- src/main/java/com/team1/otvoo/feed/service/FeedServiceImpl.java
- src/test/java/com/team1/otvoo/feed/repository/FeedRepositoryCustomImplTest.java
- src/test/java/com/team1/otvoo/feed/service/FeedLikeServiceTest.java
- src/test/java/com/team1/otvoo/feed/service/FeedServiceTest.java
KAN-166
- 피드 좋아요 및 좋아요 취소 기능 구현
- 관련 테스트 코드 수정
- 피드 좋아요 Service 단위테스트 작성
어떤 변경 사항이 있나요?
> [피드 관리] feat: KAN-166 피드 좋아요 기능 구현

- src/main/java/com/team1/otvoo/config/BatchConfig.java
- src/main/java/com/team1/otvoo/weather/batch/WeatherItemReader.java
- src/main/java/com/team1/otvoo/weather/batch/WeatherItemWriter.java
KAN-246
Batch 관련 인프라 구성 및
Reader, Writer 구현
추후 해당 구현 사항을 가지고 온디맨드 방식의 조회, Batch 관련 스케줄링에서 활용할 예정입니다.
어떤 변경 사항이 있나요?
> [날씨 데이터 관리] feat: KAN-246 날씨 관련 batch 구성

- src/main/java/com/team1/otvoo/comment/controller/CommentController.java
- src/main/java/com/team1/otvoo/comment/entity/FeedComment.java
- src/main/java/com/team1/otvoo/comment/mapper/CommentMapper.java
- src/main/java/com/team1/otvoo/comment/repository/CommentRepository.java
- src/main/java/com/team1/otvoo/comment/service/CommentService.java
- src/main/java/com/team1/otvoo/comment/service/CommentServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/comment/service/CommentServiceTest.java
KAN-274
- 댓글 등록 기능 구현
- 댓글 등록 기능 Service 단위테스트 작성
어떤 변경 사항이 있나요?
> [댓글 관리] feat: KAN-274 댓글 등록 기능 구현

- src/main/java/com/team1/otvoo/clothes/controller/ClothesController.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesCreateRequest.java
- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesSelectedValue.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesType.java
- src/main/java/com/team1/otvoo/clothes/mapper/ClothesMapper.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeValueRepository.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImpl.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesService.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesServiceImpl.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefControllerTest.java
- src/test/java/com/team1/otvoo/clothes/controller/ClothesControllerTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImplTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesServiceImplTest.java
KAN-57
의상 등록 수정 삭제 구현
어떤 변경 사항이 있나요?
> [의상 관리] feat: KAN-57 의상 등록 수정 삭제

- src/main/java/com/team1/otvoo/auth/service/AuthService.java
- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
- src/main/java/com/team1/otvoo/config/converter/SortByConverter.java
- src/main/java/com/team1/otvoo/config/props/AdminProps.java
- src/main/java/com/team1/otvoo/config/props/DefaultProfileImageProperties.java
- src/main/java/com/team1/otvoo/security/AdminInitializer.java
- src/main/java/com/team1/otvoo/security/SecurityConfig.java
- src/main/java/com/team1/otvoo/user/service/ProfileImageServiceImpl.java
- src/main/resources/application.yml
- src/test/java/com/team1/otvoo/user/resolver/ProfileImageUrlResolverTest.java
KAN-301 
- 서버 시작시 어드민 계정 초기화
어떤 변경 사항이 있나요?
> [사용자 관리] feat: KAN-301 서버 시작시 어드민 계정 초기화

- src/main/java/com/team1/otvoo/security/JwtAuthenticationFilter.java
- src/main/java/com/team1/otvoo/security/JwtLoginSuccessHandler.java
- src/test/java/com/team1/otvoo/auth/controller/AuthControllerTest.java
- src/test/java/com/team1/otvoo/auth/integration/AuthIntegrationTest.java
- src/test/java/com/team1/otvoo/auth/service/AuthServiceImplTest.java
- src/test/java/com/team1/otvoo/auth/service/EmailServiceImplTest.java
- src/test/java/com/team1/otvoo/auth/token/RedisAccessTokenStoreTest.java
- src/test/java/com/team1/otvoo/auth/token/RedisRefreshTokenStoreTest.java
- src/test/java/com/team1/otvoo/auth/token/RedisTemporaryPasswordStoreTest.java
KAN-307
인증 관련 테스트 코드 작성
어떤 변경 사항이 있나요?
> [인증 관리] test: KAN-307 인증 관련 테스트 코드 작성

- src/main/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefController.java
- src/main/java/com/team1/otvoo/clothes/controller/ClothesController.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesDtoCursorResponse.java
- src/main/java/com/team1/otvoo/clothes/dto/ClothesSearchCondition.java
- src/main/java/com/team1/otvoo/clothes/dto/SortDirection.java
- src/main/java/com/team1/otvoo/clothes/entity/ClothesType.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesRepository.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesRepositoryCustom.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImpl.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesService.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesServiceImpl.java
- src/test/java/com/team1/otvoo/clothes/controller/ClothesControllerTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesServiceImplTest.java
KAN-58
의상 목록 조회 구현
목록 조회 테스트 코드 작성
의상 속성 dto 검증 추가
의상 속성 리팩토링
어떤 변경 사항이 있나요?
> [의상 관리] feat: KAN-58 의상 목록 조회

- src/main/java/com/team1/otvoo/config/WebSocketConfig.java
- src/main/java/com/team1/otvoo/directmessage/controller/DirectMessageController.java
- src/main/java/com/team1/otvoo/directmessage/repository/DirectMessageRepositoryCustom.java
- src/main/java/com/team1/otvoo/directmessage/repository/DirectMessageRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/directmessage/service/DirectMessageService.java
- src/main/java/com/team1/otvoo/directmessage/service/DirectMessageServiceImpl.java
- src/test/java/com/team1/otvoo/directmessage/controller/DirectMessageControllerTest.java
- src/test/java/com/team1/otvoo/directmessage/integration/DirectMessageIntegrationTest.java
- src/test/java/com/team1/otvoo/directmessage/repository/DirectMessageRepositoryCustomImplTest.java
- src/test/java/com/team1/otvoo/directmessage/service/DirectMessageServiceImplTest.java
KAN-321
목록 조회 API 쿼리 파라미터 및 로직 수정
어떤 변경 사항이 있나요?
> [DM] fix: KAN-321 목록 조회 API 쿼리 파라미터 및 로직 수정

- src/main/java/com/team1/otvoo/weather/batch/WeatherForecastProcessor.java
- src/main/java/com/team1/otvoo/weather/batch/WeatherItemReader.java
- src/main/java/com/team1/otvoo/weather/client/WeatherClient.java
- src/main/java/com/team1/otvoo/weather/controller/WeatherForecastController.java
- src/main/java/com/team1/otvoo/weather/dto/VilageFcstResponse.java
- src/main/java/com/team1/otvoo/weather/dto/WeatherDto.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherHumidity.java
- src/main/java/com/team1/otvoo/weather/entity/WeatherTemperature.java
- src/main/java/com/team1/otvoo/weather/factory/WeatherForecastFactory.java
- src/main/java/com/team1/otvoo/weather/mapper/WeatherMapper.java
- src/main/java/com/team1/otvoo/weather/service/WeatherForecastService.java
- src/main/java/com/team1/otvoo/weather/service/WeatherForecastServiceImpl.java
- src/main/java/com/team1/otvoo/weather/util/WeatherComparisonUtils.java
- src/main/java/com/team1/otvoo/weather/util/WeatherTimeCalculator.java
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/weather/factory/WeatherForecastFactoryTest.java
- src/test/java/com/team1/otvoo/weather/factory/WeatherForecastPersistenceTest.java
KAN-64
WeatherForecast 서비스 구현체 생성  및 컨트롤러 구현
+
api 응답 내에서 시간관련 타입을 Instant -> LocalDateTime으로 변경
어떤 변경 사항이 있나요?
> [날씨 데이터 관리] feat: KAN-64 forecast 조회 api 구현

- src/main/java/com/team1/otvoo/weather/batch/WeatherForecastProcessor.java
- src/main/java/com/team1/otvoo/weather/client/WeatherClient.java
- src/main/java/com/team1/otvoo/weather/factory/WeatherForecastFactory.java
- src/main/java/com/team1/otvoo/weather/service/WeatherForecastServiceImpl.java
- src/main/java/com/team1/otvoo/weather/util/WeatherTimeCalculator.java
KAN-339
온디맨드 관련 사항 baseTime 수정 및 TMX,TMN이 랜더링 되지 않은 사항 해결
어떤 변경 사항이 있나요?
> [날씨 데이터 관리] refactor: KAN-339 온디맨드 관련 코드 수정

- src/main/java/com/team1/otvoo/weather/util/WeatherTimeCalculator.java
KAN-347
baseTime을 현재시간에 가장 가까운 과거 시간으로 설정
어떤 변경 사항이 있나요?
> [날씨 데이터 관리] feat: KAN-347 baseTime을 현재시간에 가장 가까운 과거 시간으로 설정

- src/main/java/com/team1/otvoo/auth/service/AuthServiceImpl.java
- src/main/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefController.java
- src/main/java/com/team1/otvoo/security/CustomAuthenticationProvider.java
- src/main/java/com/team1/otvoo/security/SecurityConfig.java
- src/main/resources/application.yml
KAN-348
- 인증 관련 리팩토링
어떤 변경 사항이 있나요?
> [인증 관리] refactor: KAN-348 인증 관련 리팩토링

- src/main/java/com/team1/otvoo/feed/service/FeedServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/feed/repository/FeedClothesRepositoryTest.java
- src/test/java/com/team1/otvoo/feed/repository/FeedRepositoryCustomImplTest.java
- src/test/java/com/team1/otvoo/feed/service/FeedServiceTest.java
- 엔티티 관계 수정에 따른 피드 코드 수정
KAN-398
- 엔티티 관계 수정에 따른 피드 코드 수정
어떤 변경 사항이 있나요?
> [피드 고도화] modify: KAN-398 피드 코드 수정

- build.gradle
- src/main/java/com/team1/otvoo/clothes/controller/ClothesController.java
- src/main/java/com/team1/otvoo/clothes/entity/Clothes.java
- src/main/java/com/team1/otvoo/clothes/extraction/candidate/AttributeCandidate.java
- src/main/java/com/team1/otvoo/clothes/extraction/candidate/AttributeCandidateRepository.java
- src/main/java/com/team1/otvoo/clothes/extraction/candidate/AttributeCandidateService.java
- src/main/java/com/team1/otvoo/clothes/extraction/dto/AnalyzeResponse.java
- src/main/java/com/team1/otvoo/clothes/extraction/dto/ClassificationResult.java
- src/main/java/com/team1/otvoo/clothes/extraction/dto/HtmlSlices.java
- src/main/java/com/team1/otvoo/clothes/extraction/pipeline/AttributeClassifier.java
- src/main/java/com/team1/otvoo/clothes/extraction/pipeline/AttributeDictionaryProvider.java
- src/main/java/com/team1/otvoo/clothes/extraction/pipeline/ClothesInfoExtractor.java
- src/main/java/com/team1/otvoo/clothes/extraction/pipeline/HtmlSliceParser.java
- src/main/java/com/team1/otvoo/clothes/extraction/service/ClothesExtractService.java
- src/main/java/com/team1/otvoo/clothes/extraction/service/ClothesExtractServiceImpl.java
- src/main/java/com/team1/otvoo/clothes/repository/ClothesAttributeDefRepository.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesImageServiceImpl.java
- src/main/java/com/team1/otvoo/clothes/service/ClothesServiceImpl.java
- src/main/java/com/team1/otvoo/exception/ErrorCode.java
- src/main/resources/schema.sql
KAN-59
링크 기반 의상 정보 추출 API 생성
LLM 의상 정보 추출
의상 수정 로직 수정
어떤 변경 사항이 있나요?
- [] 코드 리팩토링
> [의상 관리] feat:KAN-59 링크 기반 의상 정보 추출

- build.gradle
- src/main/java/com/team1/otvoo/config/RetryConfig.java
- src/main/java/com/team1/otvoo/notification/entity/AsyncTaskFailure.java
- src/main/java/com/team1/otvoo/notification/event/NotificationEvent.java
- src/main/java/com/team1/otvoo/notification/event/NotificationEventHandler.java
- src/main/java/com/team1/otvoo/notification/repository/AsyncTaskFailureRepository.java
- src/main/java/com/team1/otvoo/notification/service/SendNotificationServiceImpl.java
- src/main/java/com/team1/otvoo/sse/event/RedisPublishService.java
- src/main/java/com/team1/otvoo/sse/event/RedisStreamService.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
- src/test/java/com/team1/otvoo/notification/service/SendNotificationServiceTest.java
KAN-431
- 알림 저장 및 발행 로직을 Spring Event 기반으로 분리하여 비동기 처리(단건, 배치)
- Redis Stream 발행 실패 시 재시도 로직 구현
- SSE 유실 메시지 복구 로직 개선
어떤 변경 사항이 있나요?
> [알림] refactor: KAN-431 알림 이벤트 발행 고도화

- src/main/resources/application-prod.yml
- src/main/resources/schema.sql
KAN-447
운영 환경 설정 파일 구성
어떤 변경 사항이 있나요?
> [운영 환경 설정] chore: KAN-447 운영환경용 설정 파일 구성

- src/test/java/com/team1/otvoo/recommendation/service/ClothesAiRecommendServiceTest.java
KAN-451
추천 결과 저장 테스트
어떤 변경 사항이 있나요?
> [테스트코드] test: KAN-451 추천 결과 저장 테스트

- src/main/java/com/team1/otvoo/exception/GlobalExceptionHandler.java
- src/main/java/com/team1/otvoo/follow/repository/FollowRepositoryCustom.java
- src/main/java/com/team1/otvoo/follow/repository/FollowRepositoryCustomImpl.java
- src/main/java/com/team1/otvoo/follow/service/FollowServiceImpl.java
- src/main/java/com/team1/otvoo/notification/repository/NotificationRepositoryCustomImpl.java
KAN-467
- 프로필 이미지 url 변환하는 로직 추가
- [알림] 알림 조회 시 회원 가입 일시 이후에 생성된 알림만 조회되도록 where 조건 추가
- 요청 파라미터 제약조건 위반 exception handler 추가
어떤 변경 사항이 있나요?
> [팔로우] fix: KAN-467 이미지 url 변환 로직 추가

- build.gradle
- src/main/java/com/team1/otvoo/feed/elasticsearch/repository/FeedSearchRepositoryCustomImpl.java
KAN-476
- 피드 조회 필터에 authorIdEquals 반영
어떤 변경 사항이 있나요?
> [버그 수정] fix: KAN-476 피드 조회 authorIdEquals 반영

- src/main/resources/application-prod.yml
KAN-484 
- oauth 로그인 버그 수정
어떤 변경 사항이 있나요?
> [버그 수정] fix: KAN-484 oAuth 로그인 버그 수정

- src/main/java/com/team1/otvoo/security/JwtLoginSuccessHandler.java
- src/main/java/com/team1/otvoo/security/OAuth2JwtLoginSuccessHandler.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
KAN-486
쿠키 환경별 http/https 분리
어떤 변경 사항이 있나요?
> [인증 관리] fix: KAN-486 쿠키 환경별 http/https 분리

- src/main/resources/application.yml
KAN-487
단순 오타 수정
어떤 변경 사항이 있나요?
> [버그 수정] fix: KAN-487 단순 오타 수정

- src/test/java/com/team1/otvoo/clothes/controller/ClothesAttributeDefControllerTest.java
- src/test/java/com/team1/otvoo/clothes/controller/ClothesControllerTest.java
- src/test/java/com/team1/otvoo/clothes/extraction/candidate/AttributeCandidateServiceTest.java
- src/test/java/com/team1/otvoo/clothes/extraction/service/ClothesExtractServiceImplTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesAttributeDefServiceImplTest.java
- src/test/java/com/team1/otvoo/clothes/service/ClothesServiceImplTest.java
KAN-454
의상 서비스 및 컨트롤러 단위 테스트 수정
의상 추출 및 속성 후보 서비스 단위 테스트 추가
어떤 변경 사항이 있나요?
> [테스트 코드] test: KAN-454 의상 관리 테스트

- src/test/java/com/team1/otvoo/user/mapper/ProfileMapperTest.java
KAN-499 
- profileMapper 테스트를 단위테스트로 수정
어떤 변경 사항이 있나요?
> [테스트 코드] fix: KAN-499 profileMapper 테스트를 단위테스트로 수정

- .github/workflows/test.yml
KAN-504
Ci 파일 내 환경변수 추가
어떤 변경 사항이 있나요?
> [운영 환경 설정] fix: KAN-504 CI 파일 수정

- .github/workflows/deploy.yml
KAN-513
태그 포맷 에러 수정
어떤 변경 사항이 있나요?
> [운영 환경 설정] fix: KAN-513 CD 파일 관련 수정

- .github/workflows/deploy.yml
[25.08.28]
[배포] otvoo release v1.2
> [배포] otvoo release v1.2

- .github/workflows/deploy.yml
KAN-520
릴리즈 버전 수정
어떤 변경 사항이 있나요?
> [운영 환경 설정] fix: KAN-521 릴리즈 버전 수정

- README.md
- docker-compose.yml
KAN-526
- readme 작성
어떤 변경 사항이 있나요?
> [readme 작성] chore: KAN-526 readme 작성

- README.md
- docker-compose.yml
[25.08.29]
otvoo release v1.5.1 업데이트
> [배포] otvoo release v1.5.1 

- src/main/java/com/team1/otvoo/config/WebSocketConfig.java
KAN-531
DM 핑퐁 시간 설정
어떤 변경 사항이 있나요?
> [버그 수정] fix: KAN-531 DM 핑퐁 시간 설정

- src/main/java/com/team1/otvoo/config/WebSocketConfig.java
[25.08.29]
otvoo release v1.6 업데이트
> [배포] otvoo release v1.6

- README.md
KAN-533
readme 파일 수정
어떤 변경 사항이 있나요?
> [readme 작성] fix: KAN-534 readme 파일 수정

- README.md
[25.08.30]
otvoo release v1.7 업데이트
> [배포] otvoo release v1.7
